
title: CV Franck BOUR
url: 'http://franckbour.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Franck Bour
tagline: Développeur Mobile
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
location: Nancy, France
email: franckbour@gmail.com
phone: 
website: franckbour.github.io #do not add http://
viadeo: franck.bour2
linkedin: franck-b-274bab23
github: franckbour
bitbucket: franckbour
twitter: '@franckbour'
#facebook: 
#google-plus: 
#snapchat: 
#instagram:  

#Update all the sections by editing the files inside _includes folder.
